-- Ascensus full schema bootstrap
-- Run once in Supabase → SQL Editor for project yargrkdfgscxknicdtrt
-- Then reload the app and sign in with THEO / TYLER / JOHN

-- ---------------------------------------------------------------------------
-- Profiles (settings / onboarding)
-- ---------------------------------------------------------------------------
create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Inventories
-- ---------------------------------------------------------------------------
create table if not exists public.food_inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  price_per_100g numeric default 0,
  protein_per_100g numeric default 0,
  carbs_per_100g numeric default 0,
  fat_per_100g numeric default 0,
  water_per_100g numeric default 0,
  stock_g numeric default 0,
  preference_score numeric default 0,
  heading text,
  pack_g numeric,
  pack_unit text,
  unit_count numeric,
  pack_price numeric,
  price_cheap numeric,
  price_middle numeric,
  price_quality numeric,
  is_custom boolean default false,
  source text default 'seed',
  created_at timestamptz not null default now()
);

create table if not exists public.exercise_inventory (
  id bigint generated by default as identity primary key,
  name text not null,
  domain text,
  muscle_group text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Logs / history
-- ---------------------------------------------------------------------------
create table if not exists public.food_logs (
  id bigint generated by default as identity primary key,
  meal_name text,
  calories numeric default 0,
  protein numeric default 0,
  carbs numeric default 0,
  fat numeric default 0,
  cost numeric default 0,
  food_details text,
  created_at timestamptz not null default now()
);

create table if not exists public.workout_logs (
  id bigint generated by default as identity primary key,
  exercise text,
  sets integer default 0,
  reps numeric default 0,
  weight_kg numeric default 0,
  distance_km numeric default 0,
  time_minutes numeric default 0,
  rpe numeric default 0,
  type text,
  session_duration_min numeric default 0,
  periodization_phase text,
  created_at timestamptz not null default now()
);

create table if not exists public.body_metrics (
  id bigint generated by default as identity primary key,
  weight_kg numeric,
  body_fat numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.user_templates (
  id bigint generated by default as identity primary key,
  type text,
  name text,
  details text,
  "sessionKind" text,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- RLS
-- Shared-dev model: any signed-in user can read/write inventory + logs.
-- Profiles stay per-user.
-- ---------------------------------------------------------------------------
alter table public.user_profiles enable row level security;
alter table public.food_inventory enable row level security;
alter table public.exercise_inventory enable row level security;
alter table public.food_logs enable row level security;
alter table public.workout_logs enable row level security;
alter table public.body_metrics enable row level security;
alter table public.user_templates enable row level security;

-- Profiles
drop policy if exists "Users can select own profile" on public.user_profiles;
drop policy if exists "Users can insert own profile" on public.user_profiles;
drop policy if exists "Users can update own profile" on public.user_profiles;
create policy "Users can select own profile"
  on public.user_profiles for select using (auth.uid() = id);
create policy "Users can insert own profile"
  on public.user_profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile"
  on public.user_profiles for update using (auth.uid() = id) with check (auth.uid() = id);

-- Shared tables (authenticated full access)
drop policy if exists "Authenticated full access food_inventory" on public.food_inventory;
drop policy if exists "Authenticated full access exercise_inventory" on public.exercise_inventory;
drop policy if exists "Authenticated full access food_logs" on public.food_logs;
drop policy if exists "Authenticated full access workout_logs" on public.workout_logs;
drop policy if exists "Authenticated full access body_metrics" on public.body_metrics;
drop policy if exists "Authenticated full access user_templates" on public.user_templates;

create policy "Authenticated full access food_inventory"
  on public.food_inventory for all to authenticated using (true) with check (true);
create policy "Authenticated full access exercise_inventory"
  on public.exercise_inventory for all to authenticated using (true) with check (true);
create policy "Authenticated full access food_logs"
  on public.food_logs for all to authenticated using (true) with check (true);
create policy "Authenticated full access workout_logs"
  on public.workout_logs for all to authenticated using (true) with check (true);
create policy "Authenticated full access body_metrics"
  on public.body_metrics for all to authenticated using (true) with check (true);
create policy "Authenticated full access user_templates"
  on public.user_templates for all to authenticated using (true) with check (true);

grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Force PostgREST to pick up new tables immediately
notify pgrst, 'reload schema';
