/** Shared mutable app state — import and mutate fields in place. */
export const store = {
  supabaseClient: null,
  currentUser: null,
  globalFoodDB: [],
  globalExerciseDB: [],
  globalTemplates: [],
  currentRefund: { cals: 0, carbs: 0 },
  globalGroupedHistory: {},
  userConfig: {
    weight: 84, targetWeight: 75, height: 180, age: 25, bodyFat: 0, sex: 'Male', activity: 1.55, goal: 'Fat_Loss',
    mealsPerDay: 3, budget: 15.00, trainingFreq: 4,
    gymWillingness: 4, maxGymTime: 90, bandAuxiliary: false, dumbbellIncrement: 2,
    dbIncrements: { low: 1, mid: 2, high: 2 },
    exerciseIncrements: {},
    /** Seed working weights by exercise name (kg). Used until real logs drive progression. */
    exerciseWorkingWeights: {},
    hybridStrengthDays: 3, hybridHypertrophyDays: 1,
    baselineTargets: { cals: 0, pro: 0, carb: 0, fat: 0 },
    targets: { cals: 0, pro: 0, carb: 0, fat: 0 },
    restStop: false, dependentAthlete: false, tdeePenalty: 0,
    diet: 'Standard', shopStyle: 'Cheap', injury: 'None', sport: 'None', repairLevel: 4,
    trainingWindow: 'Afternoon', seasonPhase: 'OffSeason_Hypertrophy',
    experience: 'Beginner', coreStrength: null, oneRepMax: { squat: 0, bench: 0, deadlift: 0 }, canDoPullups: 'Yes',
    guidanceOff: { food: false, workout: false, timetabling: false },
    injuryRecord: null,
    networkEnabled: true,
    networkUsername: '',
    networkPrivate: true,
    networkShowStreak: true,
    networkShowLift: true
  },
  activeLog: { type: 'breakfast', items: [] },
  /** Manual gym session rest prefs: { active, custom, compoundSec, isolationSec } | null */
  manualGymRest: null,
  consumedToday: { cals: 0, pro: 0, carb: 0, fat: 0, cost: 0, mealsLogged: 0, water: 0 },
  fatigueLockouts: {},
  offlineQueue: JSON.parse(localStorage.getItem('ascensus_offline_queue')) || [],
  unifiedChartInstance: null,
  macroChartInstance: null,
  dailyFitnessTargets: { str: 0, pow: 0, spd: 0, crd: 0, end: 0 },
  currentFitnessScore: { str: 0, pow: 0, spd: 0, crd: 0, end: 0 },
  ghostOverrides: {},
  currentGhostItems: [],
  modalExerciseChartInstance: null,
  restIntervals: {},
  exerciseChartInstance: null,
  savedTargets: JSON.parse(localStorage.getItem('ascensus_metric_targets')) || {},
  _weekPlanCache: { key: '', plan: null },
  specificSchedules: {},
};
